name: "release"

on:
  push:
    branches: [release]

jobs:
  check:
    uses: vodyani/workflows/.github/workflows/pre-check.yml@master

  publish_package:
    needs: check
    uses: vodyani/workflows/.github/workflows/publish-npm-package.yml@master
    secrets:
      NPM_CI_TOKEN: ${{ secrets.NPM_CI_TOKEN }}

  publish_release:
    needs: [publish_package]
    uses: vodyani/workflows/.github/workflows/publish-release.yml@master
    secrets:
      GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
